[versions]
# When upgrading JaCoCo to a newer version, make sure to
# check the comment in the OpenAnalyzer.java, JaCoCoPreMain.java and CachingInstructionsBuilder.java
# and update the internal_xxxxxx hash included in the imports in LenientCoverageTransformer.java and JaCoCoPreMain.java.
jacoco = "0.8.14"
# We need to stay on the 1.3.x release line as 1.4.x requires Java 11
logback = "1.3.16"
retrofit = "3.0.0"
okhttp = "5.3.2"
mockito = "5.20.0"
mockitoKotlin = "6.1.0"
picocli = "4.7.7"
maven = "3.9.11"
asm = "9.9"

[libraries]
jetty-bom = { module = "org.eclipse.jetty:jetty-bom", version = "9.4.58.v20250814" }
jetty-server = { module = "org.eclipse.jetty:jetty-server" }
jetty-servlet = { module = "org.eclipse.jetty:jetty-servlet" }

jersey-bom = { module = "org.glassfish.jersey:jersey-bom", version = "2.47" }
jersey-server = { module = "org.glassfish.jersey.core:jersey-server" }
jersey-containerJettyHttp = { module = "org.glassfish.jersey.containers:jersey-container-jetty-http" }
jersey-containerServletCore = { module = "org.glassfish.jersey.containers:jersey-container-servlet-core" }
jersey-mediaJsonJackson = { module = "org.glassfish.jersey.media:jersey-media-json-jackson" }
jersey-hk2 = { module = "org.glassfish.jersey.inject:jersey-hk2" }

jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version = "2.20.1" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }

jakarta-activation-api = { module = "jakarta.activation:jakarta.activation-api", version = "1.2.2" }

jacoco-core = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco" }
jacoco-report = { module = "org.jacoco:org.jacoco.report", version.ref = "jacoco" }
jacoco-agent = { module = "org.jacoco:org.jacoco.agent", version.ref = "jacoco" }

logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "retrofit" }

okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

spark = { module = "com.sparkjava:spark-core", version = "2.9.4" }
jcommander = { module = "com.beust:jcommander", version = "1.82" }
commonsCodec = { module = "commons-codec:commons-codec", version = "1.20.0" }
commonsLang = { module = "org.apache.commons:commons-lang3", version = "3.20.0" }
commonsIo = { module = "commons-io:commons-io", version = "2.21.0" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version = "7.4.0.202509020913-r" }
okio = { module = "com.squareup.okio:okio", version = "3.16.4" }

picocli-core = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version = "5.18.1" }

log4j-core = { module = "org.apache.logging.log4j:log4j-core", version = "2.25.2" }

junit-bom = { module = "org.junit:junit-bom", version = "6.0.1" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine" }
junit-platform-commons = { module = "org.junit.platform:junit-platform-commons" }

junit4 = { module = "junit:junit", version = "4.13.2" }
assertj = { module = "org.assertj:assertj-core", version = "3.27.6" }
jsonassert = { module = "org.skyscreamer:jsonassert", version = "1.5.3" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }

maven-core = { module = "org.apache.maven:maven-core", version.ref = "maven" }
maven-pluginApi = { module = "org.apache.maven:maven-plugin-api", version.ref = "maven" }
maven-pluginAnnotations = { module = "org.apache.maven.plugin-tools:maven-plugin-annotations", version = "3.15.2" }

asm-core = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }

jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2-1" }

[plugins]
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
pluginPublish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
gitProperties = { id = "com.gorylenko.gradle-git-properties", version = "2.5.4" }
mavenPluginDevelopment = { id = "org.gradlex.maven-plugin-development", version = "1.0.3" }
shadow = { id = "com.gradleup.shadow", version = "9.3.0" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
jlink = { id = "org.beryx.jlink", version = "3.1.3" }
